(function initConstants(global) {
  const namespace = (global.InovaBookmarks = global.InovaBookmarks || {});

  namespace.constants = {
    storageKeys: {
      settings: "settings",
      pausedSessions: "pausedSessions",
      uiPreferences: "uiPreferences",
      providerIdentityCache: "providerIdentityCache",
      productLaneMigration: "productLaneMigration",
    },
    defaults: {
      settings: {
        enabled: true,
        autoBookmark: true,
        meetingDebugConsoleEnabled: false,
        meetingWorkspaceTarget: "production",
        meetingWorkspaceUrlOverride: "",
      },
      pausedSessions: {},
      promptReview: {
        copyState: "idle",
        error: "",
        lastReviewedAt: "",
        open: false,
        pending: false,
        placeholderConfirmation: false,
        requestId: 0,
        result: null,
        reviewedText: "",
      },
      providerIdentityCache: {
        version: 1,
        providerIdentity: {
          provider: "inova",
          available: false,
          providerUserKey: "",
          email: "",
          displayName: "",
          numericUserId: null,
        },
      },
      productLaneMigration: {
        version: 1,
        attemptCount: 0,
        startedAt: "",
        completedAt: "",
        sourceLane: "",
        targetLane: "",
        sourceRevision: "",
        lastError: "",
      },
      uiPreferences: {
        activeTool: "bookmarks",
        activePromptTab: "library",
        panelOpen: false,
        handleRatios: {
          wide: 0.38,
          compact: 0.46,
        },
      },
    },
    selectors: {
      chatMessageLog: '[aria-label="채팅 메시지 목록"]',
      currentModelButton: "button",
      messageArticle: "article",
      userMessage: ".chat-message--user",
      userText: ".chat-message__text",
      assistantMessage: ".chat-message--assistant, .chat-message--ai, .chat-message--bot",
      assistantText: ".chat-message__text",
      chatLog: '[aria-label="채팅 기록"]',
      chatScroller: "main.chat-history__content, .chat-history__content, .chat-history",
      mainHeading: "h1",
      messageItem: "article",
      composer:
        'textarea.chat-input__textarea, textarea[placeholder*="무엇이든 입력하고 대화하세요"], textarea, [role="textbox"], [contenteditable="true"]',
    },
    storeCategories: [
      { id: "all", label: "전체" },
      { id: "document", label: "문서 작성" },
      { id: "summary", label: "요약/정리" },
      { id: "analysis", label: "분석/리서치" },
      { id: "meeting", label: "회의/업무" },
      { id: "translation", label: "번역" },
      { id: "advertising", label: "광고/퍼포먼스" },
      { id: "marketing", label: "마케팅" },
      { id: "commerce", label: "커머스" },
      { id: "sales", label: "세일즈" },
      { id: "customer-success", label: "고객 성공/CS" },
      { id: "hr", label: "HR/피플" },
      { id: "finance", label: "재무/경영관리" },
      { id: "code", label: "코딩" },
      { id: "core-dev", label: "코어 개발" },
      { id: "language-specialists", label: "언어/프레임워크" },
      { id: "infrastructure", label: "인프라" },
      { id: "quality-security", label: "품질/보안" },
      { id: "data-ai", label: "데이터/AI" },
      { id: "developer-experience", label: "개발 경험" },
      { id: "specialized-domains", label: "전문 도메인" },
      { id: "business-product", label: "비즈니스/프로덕트" },
      { id: "meta-orchestration", label: "오케스트레이션" },
      { id: "research-analysis", label: "리서치/분석" },
      { id: "other", label: "기타" }
    ],
    limits: {
      queryPreviewLength: 120,
    },
  };
})(globalThis);
